### ISSUE TITLE
inappropriate de-structure of `this[state_symbol]` in `next()`

### ISSUE THREAD

**Issue by chazkiker2** [Light-Labs/ryderserial-proto#4]
https://github.com/Light-Labs/ryderserial-proto/blob/1d478552f89d07a8ca4937cb7a0f7f5f36edaf35/src/index.js#L346

we confirm on [this line](https://github.com/Light-Labs/ryderserial-proto/blob/1d478552f89d07a8ca4937cb7a0f7f5f36edaf35/src/index.js#L340) above that `this[state_symbol] === STATE_IDLE` and proceed to attempt a de-structure like so: 

```typescript
var [, , reject] = this[state_symbol];
```

This de-structure always fail and certainly throw an error due to the fact that `this[state_symbol]` will never contain anything other than `STATE_IDLE`, `STATE_SENDING`, or `STATE_READING`

It's likely that this line was meant to reference `this[train_symbol][SOME_INDEX]` but I am not yet sure what `SOME_INDEX` should be.

**Comment by MarvinJanssen** [comment]
👍

Likely meant to be `var [,,reject] = this[train_symbol][0];`

Although it would probably make more sense to call `this.clear()` and then reject.

**Comment by chazkiker2** [comment]
Sweet! Just tossed those in [the TS PR](https://github.com/Light-Labs/ryderserial-proto/pull/5/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.ts&hide-deleted-files=true#r634906769) 

(PR #5)

**Comment by chazkiker2** [comment]
This was resolved in #5
